app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('doctolib.urls')),
]

doctolib/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'doctolib'
urlpatterns = [
    path('home_patient/', views.home_patient, name='home_patient'),
    path('backoffice_practicien/', views.backoffice_practicien, name='backoffice_practicien'),
    path('<int:appointment_id>/invoice/', views.invoice, name='invoice'),
    path('', views.base, name='base'),
    path('registration_patient/', views.registration_patient, name='registration_patient'),
    path('registration_practicien/', views.registration_practicien, name='registration_practicien'),
]

doctolib/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User


class Prestation(models.Model):
    titre = models.CharField(max_length=200)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.titre
    
class Profession(models.Model):
    user = models.ForeignKey(User, related_name='practicien_profession', on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    prestations = models.ForeignKey(Prestation, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

class Appointment(models.Model):
    date = models.DateTimeField('appointment date')
    practicien = models.ForeignKey(User, related_name='practicien_appointments', on_delete=models.CASCADE)
    patient = models.ForeignKey(User, related_name='patient_appointments', on_delete=models.CASCADE)
    prestation = models.ForeignKey(Prestation, on_delete=models.CASCADE)
    price_prestation = models.IntegerField(default=0)

class prestation_practicien(models.Model):
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE)
    practicien = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.IntegerField()

doctolib/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Appointment, Profession

# Create your forms here.

class NewPracticientForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewPracticientForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class NewPatientForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewPatientForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class NewPrestationForm(forms.Form):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewPatientForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class AppointmentForm(forms.Form):
    class Meta:
        model = Appointment
        fields = ['date', 'practicien', 'prestation']

class ProfessionForm(forms.Form):
    class Meta:
        model = Profession
        fields = ['description', 'prestations']


class PriceForm(forms.Form):
    your_price = forms.IntegerField(required=True)

    def save(self, commit=True):
            appointment = super(PriceForm, self).save(commit=False)
            appointment.price_prestation = self.cleaned_data['your_price']
            if commit:
                appointment.save()
            return appointment

app/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

def index(request):
    return HttpResponse('hello world')

doctolib/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render,  redirect, get_object_or_404
from . forms import NewPatientForm, NewPracticientForm
from .models import Prestation, Profession, Appointment, prestation_practicien
from django.contrib.auth import login
from django.contrib.auth.models import User
from .forms import PriceForm
from django.contrib import messages

def base(request):
    context = {"message": "Bienvenue"}
    return render(request, 'doctolib/base.html', context)

def home_patient(request):
    current_user = request.user
    user = get_object_or_404(User, pk=current_user.id)

    return render(request, 'doctolib/home_patient.html', {
        'user': user,
    })

def registration_patient(request):
    if request.method == "POST":
        form = NewPatientForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("doctolib:home_patient")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewPatientForm()
    return render (request=request, template_name="doctolib/registration_patient.html", context={"register_form":form})

def registration_practicien(request):
    if request.method == "POST":
        form = NewPracticientForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("doctolib:home_patient")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewPracticientForm()
    return render (request=request, template_name="doctolib/registration_practicien.html", context={"register_form":form})
    return render(request, 'doctolib/registration_practicien.html')

def backoffice_practicien(request):
    current_user = request.user
    user = get_object_or_404(User, pk=current_user.id)

    return render(request, 'doctolib/backoffice_practicien.html', {
        'user': user,
    })

def invoice(request, appointment_id):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PriceForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            appointment = form.save()
            Appointment(request, appointment)
            messages.success(request, "Prix modifié avec succès." )
            return redirect("main:homepage")
        messages.error(request, "Echec de modif prix")
    form = PriceForm()
    return render (request=request, template_name="doctolib/invoice.html", context={"form":form})
    return render(request, 'doctolib/invoice.html.html')

app/templates/app/basic_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% if user.is_authenticated %}
    <li>Connecté en tant que: {{ user.get_username }}</li>
    <li><a href="{% url 'logout'%}?next={{request.path}}">Déconnexion</a></li>
    {% else %}
    <li><a href="{% url 'login'%}?next={{request.path}}">Connexion</a></li>
    {% endif %}
</body>

</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'doctolib/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'doctolib/nav.js' %}"></script>
    <title>Allo Docteur !</title>
</head>

<body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="#">Home</a>
        <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="fas fa-tachometer-alt"></i></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="javascript:void(0);"><i class="fas fa-tachometer-alt"></i>Home</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Calendar</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>{{ user.get_username }}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Inscription</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-copy"></i>Documents</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctolib:home_patient'%}"><i class="far fa-address-book"></i>Mes Rendez-vous</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctolib:backoffice_practicien'%}"><i class="far fa-address-book"></i>Backoffice Practicien</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}?next=/"><i class="far fa-address-book"></i>Déconnexion</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}?next={{request.path}}"><i class="far fa-address-book"></i>Connexion</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</body>

</html>

doctolib/templates/doctolib/backoffice_practicien.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plateforme de Gestion Practicien</title>
</head>

<body>
    {% include "base.html" %}

    <h3>Votre profession : {{ user.practicien_profession.get }}</h3> 
    <br/>
    <h3>Vos rdv en attente : </h3>
    <ul>
        {% for appointment in user.practicien_appointments.all %}
            <li>
                Patient : {{ appointment.patient }} | Prestation : {{ appointment.prestation }}
            </li>
            <a href="{% url 'doctolib:invoice' appointment.id %}">Facturer le rdv</a>
        {% endfor %}
    </ul>
</body>

</html>

doctolib/templates/doctolib/home_patient.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'doctolib/table.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'doctolib/table.js' %}"></script>
    <title>Bienvenue {{ user.username }}</title>
</head>

<body>
    {% include "doctolib/base.html" %}

    <section>
        <!--for demo wrap-->
        {% for appointment in user.patient_appointments.all %}
        <h1>Vos rendez-vous</h1>
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Docteur</th>
                <th>Prestation</th>
                <th>Horaire</th>
                <th>Prix</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
                <tr>
                    <td>{{ appointment.practicien }}</td>
                    <td>{{ appointment.prestation }}</td>
                    <td>01/01/2022 13h00</td>
                    <td>10€</td>
                </tr>
            </tbody>
          </table>
        </div>
        {% endfor %}

        {% for appointment in user.practicien_appointments.all %}
        <h1>Fixed Table header</h1>
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Patient</th>
                <th>Prestation</th>
                <th>Horaire</th>
                <th>Prix</th>
                <th>Facture</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
                <tr>
                    <td>{{ appointment.patient }}</td>
                    <td>{{ appointment.practicien }}</td>
                    <td>01/01/2022 13h00</td>
                    <td>10€</td>
                    <td><a href="#">Facturation</a></td>
                </tr>
            </tbody>
          </table>
        </div>
        {% endfor %}
      </section>
</body>

</html>

doctolib/templates/doctolib/invoice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% include "base.html" %}

    <form action="/hello" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Confirmer">
    </form>
</body>

</html>

doctolib/templates/doctolib/registration_patient.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'doctolib/login.css' %}">
    <script src="{% static 'doctolib/login.js' %}"></script>
    <title>Inscription</title>
</head>

<body>
    {% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please
        try again.</p>
    {% endif %}
    {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page.
        To proceed,
        please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
    {% endif %}
    <div class="container right-panel-active" id="container">
        <div class="form-container sign-up-container">
            <form method="post" action="{% url 'doctolib:registration_patient' %}">
                {% csrf_token %}
                <h1>Create Account</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                {{ register_form.username }}
                {{ register_form.email }}
                {{ register_form.password1 }}
                {{ register_form.password2 }}
                <button class="button">Sign Up</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="button ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start journey with us</p>
                    <a class="button ghost" id="signUp" href="{% url 'doctolib:registration_patient' %}">Inscription Patient</a>
                    <a class="button ghost" id="signUp" href="{% url 'doctolib:registration_practicien' %}">Inscription Practicien</a>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

</html>

doctolib/templates/doctolib/registration_practicien copy.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
</head>

<body>
    {% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please
        try again.</p>
    {% endif %}
    {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page.
        To proceed,
        please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
    {% endif %}
    <form method="post" action="{% url 'registration_practicien' %}">
        {% csrf_token %}
        {{ register_form}}
        <div>
            <input type="submit" value="Inscription" />
            <input type="hidden" name="next" value="{{ next }}" />
        </div>
    </form>
    {# Assumes you setup the password_reset view in your
    URLconf #}
    <div>
        <p><a href="{% url 'password_reset' %}">Mot de passe oublier 
            ?</a></p>
        <p><a href="{% url 'registration_patient' %}">Inscription
            Patient?</a></p>
    </div>
    {% endblock %}
    
</body>

</html>

doctolib/templates/doctolib/registration_practicien.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'doctolib/login.css' %}">
    <script src="{% static 'doctolib/login.js' %}"></script>
    <title>Inscription</title>
</head>

<body>
    {% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please
        try again.</p>
    {% endif %}
    {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page.
        To proceed,
        please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
    {% endif %}
    <div class="container right-panel-active" id="container">
        <div class="form-container sign-up-container">
            <form method="post" action="{% url 'doctolib:registration_practicien' %}">
                {% csrf_token %}
                <h1>Create Account</h1>
                <div class="social-container">
                    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                {{ register_form.username }}
                {{ register_form.email }}
                {{ register_form.password1 }}
                {{ register_form.password2 }}
                <button class="button">Sign Up</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="button ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start journey with us</p>
                    <a class="button ghost" id="signUp" href="{% url 'doctolib:registration_patient' %}">Inscription Patient</a>
                    <a class="button ghost" id="signUp" href="{% url 'doctolib:registration_practicien' %}">Inscription Practicien</a>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

</html>